on:
  push:

name: Hello World

jobs:
  hello:
    runs-on: ubuntu-latest
    name: Says Hello World
    permissions:
        contents: read
        id-token: write
    steps:
    - name: Say it
      run: echo "Hello World"
