on:
  push:

name: Hello World

env:
  hashiUrl: https://vault-cluster-id-test-ed-public-vault-ff55f991.2f7cb571.z1.hashicorp.cloud:8200
  roleName: gha-test-role
  audience: gha-medium
  namespace: admin

jobs:
  hello:
    runs-on: ubuntu-latest
    name: Says Hello World
    permissions:
        contents: read
        id-token: write
    steps:
    - name: Say it
      run: echo "Hello World"
    - name: perform token run
      run: |
        echo $(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=gha-medium" | base64)
      shell: bash
    - name: Retreive Secrets
      id: retrieve-secrets
      uses: hashicorp/vault-action@v2.4.1
      with:
        url: ${{ env.hashiUrl }}
        role: ${{ env.roleName }}
        method: jwt
        jwtGithubAudience: ${{ env.audience }}
        namespace: ${{ env.namespace }}
        tlsSkipVerify: false
        exportEnv: true
        secrets: |
          secret/apikeys/ deploymentServer | DEPLOYMENT_KEY
